import { PDFDocument, StandardFonts, rgb, PDFFont } from "pdf-lib";

type PdfSection = {
  heading: string;
  paragraphs: string[];
};

const PAGE = {
  width: 595.28, // Exact A4 width in points
  height: 841.89, // Exact A4 height in points
  marginTop: 60,
  marginBottom: 60,
  marginX: 50,
};

const COLOR = {
  brand: rgb(0.09, 0.29, 0.48), // Deep Blue
  brandLight: rgb(0.96, 0.97, 0.98), // Very soft cool gray/blue for backgrounds
  text: rgb(0.15, 0.18, 0.22), // Dark Slate (softer than pure black)
  muted: rgb(0.45, 0.5, 0.55), // Muted gray for dates/footers
  border: rgb(0.85, 0.88, 0.92), // Light border color
};

const normalizeText = (value: string): string =>
  value.trim().replace(/\s+/g, " ");

// 1. Replaced character-count wrapping with precise font-width metric wrapping
const wrapText = (
  text: string,
  maxWidth: number,
  font: PDFFont,
  fontSize: number,
): string[] => {
  const cleaned = normalizeText(text);
  if (!cleaned) return [];

  const words = cleaned.split(" ");
  const lines: string[] = [];
  let currentLine = "";

  for (const word of words) {
    const testLine = currentLine ? `${currentLine} ${word}` : word;
    const width = font.widthOfTextAtSize(testLine, fontSize);

    if (width > maxWidth) {
      if (currentLine) lines.push(currentLine);
      currentLine = word;
    } else {
      currentLine = testLine;
    }
  }
  if (currentLine) lines.push(currentLine);

  return lines;
};

export const buildModulePdf = async (
  title: string,
  sections: PdfSection[],
): Promise<Buffer> => {
  const doc = await PDFDocument.create();
  const regular = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);

  let page = doc.addPage([PAGE.width, PAGE.height]);
  let y = PAGE.height - PAGE.marginTop;
  let pageNumber = 1;

  const drawHeader = () => {
    // Elegant, clean text header rather than a heavy block
    page.drawText("LIFEPLAN JOURNEY", {
      x: PAGE.marginX,
      y: PAGE.height - 40,
      size: 9,
      color: COLOR.brand,
      font: bold,
    });

    page.drawLine({
      start: { x: PAGE.marginX, y: PAGE.height - 50 },
      end: { x: PAGE.width - PAGE.marginX, y: PAGE.height - 50 },
      thickness: 0.5,
      color: COLOR.border,
    });
  };

  const drawFooter = () => {
    const footerY = PAGE.marginBottom - 20;

    page.drawLine({
      start: { x: PAGE.marginX, y: footerY + 15 },
      end: { x: PAGE.width - PAGE.marginX, y: footerY + 15 },
      thickness: 0.5,
      color: COLOR.border,
    });

    page.drawText("Generated by LifePlan", {
      x: PAGE.marginX,
      y: footerY,
      size: 8,
      color: COLOR.muted,
      font: regular,
    });

    page.drawText(`Page ${pageNumber}`, {
      x: PAGE.width - PAGE.marginX - 30,
      y: footerY,
      size: 8,
      color: COLOR.muted,
      font: regular,
    });
  };

  const ensureSpace = (requiredHeight: number) => {
    if (y - requiredHeight < PAGE.marginBottom) {
      drawFooter();
      page = doc.addPage([PAGE.width, PAGE.height]);
      pageNumber += 1;
      drawHeader();
      y = PAGE.height - PAGE.marginTop - 20;
    }
  };

  // --- Start Drawing Document ---

  drawHeader();
  y -= 10;

  // Title Section
  const titleSize = 22;
  const titleLines = wrapText(
    title,
    PAGE.width - PAGE.marginX * 2,
    bold,
    titleSize,
  );
  for (const line of titleLines) {
    ensureSpace(titleSize + 10);
    page.drawText(line, {
      x: PAGE.marginX,
      y,
      size: titleSize,
      color: COLOR.brand,
      font: bold,
    });
    y -= titleSize + 8;
  }

  y -= 2;

  // Metadata / Date
  const dateText = `Generated: ${new Date().toLocaleDateString()}`;
  page.drawText(dateText, {
    x: PAGE.marginX,
    y,
    size: 10,
    color: COLOR.muted,
    font: regular,
  });

  y -= 12;
  page.drawLine({
    start: { x: PAGE.marginX, y },
    end: { x: PAGE.width - PAGE.marginX, y },
    thickness: 0.5,
    color: COLOR.border,
  });
  y -= 25;

  // Sections
  for (const section of sections) {
    const validParagraphs = section.paragraphs
      .map(normalizeText)
      .filter(Boolean);
    if (!section.heading && validParagraphs.length === 0) continue;

    const contentMaxWidth = PAGE.width - PAGE.marginX * 2 - 24; // Padding for left accent
    const headingSize = 13;
    const bodySize = 10.5;

    // Pre-calculate heights to handle pagination smoothly
    const headingLines = wrapText(
      section.heading,
      contentMaxWidth,
      bold,
      headingSize,
    );
    let sectionHeight =
      headingLines.length > 0 ? headingLines.length * (headingSize + 6) + 8 : 0;

    const paragraphLinesList: string[][] = [];
    for (const p of validParagraphs) {
      const pLines = wrapText(p, contentMaxWidth, regular, bodySize);
      paragraphLinesList.push(pLines);
      sectionHeight += pLines.length * (bodySize + 6) + 8;
    }

    sectionHeight += 12; // Extra padding inside the section

    // Ensure the whole block fits, or push to the next page
    ensureSpace(sectionHeight + 20);

    // 2. Modern UI Pattern: Soft background + Thick left accent border
    page.drawRectangle({
      x: PAGE.marginX,
      y: y - sectionHeight + 10,
      width: PAGE.width - PAGE.marginX * 2,
      height: sectionHeight,
      color: COLOR.brandLight,
    });

    page.drawRectangle({
      x: PAGE.marginX,
      y: y - sectionHeight + 10,
      width: 4, // Thick left accent line
      height: sectionHeight,
      color: COLOR.brand,
    });

    const textX = PAGE.marginX + 16; // Shift text right to avoid accent line
    y -= 4;

    // Draw Heading
    if (headingLines.length > 0) {
      for (const line of headingLines) {
        page.drawText(line, {
          x: textX,
          y,
          size: headingSize,
          color: COLOR.brand,
          font: bold,
        });
        y -= headingSize + 6;
      }
      y -= 4;
    }

    // Draw Paragraphs
    for (const lines of paragraphLinesList) {
      for (const line of lines) {
        page.drawText(line, {
          x: textX,
          y,
          size: bodySize,
          color: COLOR.text,
          font: regular,
        });
        y -= bodySize + 6;
      }
      y -= 8; // Space between paragraphs
    }

    y -= 20; // Space below the entire section
  }

  drawFooter();

  const bytes = await doc.save();
  return Buffer.from(bytes);
};
